// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_h_qWxfsVcgV4zBQv9xDmI3OAnOzOKLw',
    appId: '1:271222119081:web:2161b7f7d279b4b36967b8',
    messagingSenderId: '271222119081',
    projectId: 'dra-logistics',
    authDomain: 'dra-logistics.firebaseapp.com',
    storageBucket: 'dra-logistics.firebasestorage.app',
    measurementId: 'G-PYG5S51H8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBVGNg3AGChbf0ZmRsrqFVgPcLa6Tgmc',
    appId: '1:271222119081:android:36a2a09e3f3130c06967b8',
    messagingSenderId: '271222119081',
    projectId: 'dra-logistics',
    storageBucket: 'dra-logistics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaAuu3vl7RajXB-ZZoE0OTaToioP3Aw80',
    appId: '1:271222119081:ios:b97b95d4d4b4fe1b6967b8',
    messagingSenderId: '271222119081',
    projectId: 'dra-logistics',
    storageBucket: 'dra-logistics.firebasestorage.app',
    iosBundleId: 'com.example.drivers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaAuu3vl7RajXB-ZZoE0OTaToioP3Aw80',
    appId: '1:271222119081:ios:b97b95d4d4b4fe1b6967b8',
    messagingSenderId: '271222119081',
    projectId: 'dra-logistics',
    storageBucket: 'dra-logistics.firebasestorage.app',
    iosBundleId: 'com.example.drivers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_h_qWxfsVcgV4zBQv9xDmI3OAnOzOKLw',
    appId: '1:271222119081:web:b910d5154bf248986967b8',
    messagingSenderId: '271222119081',
    projectId: 'dra-logistics',
    authDomain: 'dra-logistics.firebaseapp.com',
    storageBucket: 'dra-logistics.firebasestorage.app',
    measurementId: 'G-JFW0J7GPE5',
  );

}